### ISSUE TITLE
`a string is not a function` / `unsupported binding form`

### ISSUE THREAD

**Issue by vemv** [redplanetlabs/rama-clj-kondo#4]
In CI I see this:

```
x.clj:169:3: error: a string is not a function
x.clj:170:6: error: unsupported binding form :>
```

While locally I see:

```
WARNING: error while trying to read hook for com.rpl.rama/defmodule: Could not resolve symbol: api/set-node?
WARNING: error while trying to read hook for com.rpl.rama/deframafn: Could not resolve symbol: api/set-node?
```

Let me know if you'd need more info.

Thanks - V

**Comment by nixin72** [comment]
For the issue locally - what version of clj-kondo do you have? `api/set-node?` is only available in `2023.03.17` or later https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md#20230317

As for the problem in CI, can you share the relevant code snippet?

**Comment by vemv** [comment]
Thanks for the response!

I now fixed my local env so that I'm using kondo latest (I had an older user-wide plugin around) - the error is identical everywhere now.

I'll try to craft a repro when I have the chance.

**Comment by vemv** [comment]
@nixin72 I've passed a repro over Clojurians Slack

**Comment by nixin72** [comment]
@vemv Fixes for both of these have just been merged in. They'll be bundled in the next release of Rama, or you can get them now by cloning the repo and adding it to your classpath.

**Comment by vemv** [comment]
Great news - thanks much!
